### ISSUE TITLE
error in exemple In this page : https://pypi.org/project/pynut3

### ISSUE THREAD

**Issue by MichelBen** [Mausy5043/python-nut3#8]
Hello,

There are error in exemple In this page : https://pypi.org/project/pynut3 

ups_dict = client.list_ups()    -> ups_dict = client.get_dict_ups()

vars_dict = client.list_vars(k1) -> vars_dict = client.get_dict_vars(k1)

**Comment by Mausy5043** [comment]
Corrected the code with v1.4.5
